version: '3'

services:
  nginx:
    image: 713366850227.dkr.ecr.us-east-2.amazonaws.com/nginx
    ports:
      - "80"  #동적포트 바인딩  호스트머신에서 접속하기위한 동적 포트를 찾아내서 접속해야함 만약 50:50 안하면  ## ecs 도 동적 포트 바인딩 해야해 안그러면 여러개 올라갈때 두번째 부터는 이미 쓰고 있는 포트가
    build: ./nginx   #폴더에 가서 알아서 읽음
    command: /bin/bash -c "sleep 10; exec nginx -g 'daemon off;'"
    hostname: app
    logging:
      driver: awslogs
      options:
        awslogs-region: "us-east-2"
        awslogs-group: ecs-personalassistant-api #그룹을 나누거나 프리픽스를 나눠서
        awslogs-stream-prefix: "nginx"

  app:
    image: 713366850227.dkr.ecr.us-east-2.amazonaws.com/flask-personalassistant-app
    build: .
    ports:
      - "5000"
    entrypoint:
      python
    command: [
      "app.py"
    ]
    hostname: app
    logging:
      driver: awslogs
      options:
        awslogs-region: "us-east-2"
        awslogs-group: ecs-personalassistant-api #그룹을 나누거나 프리픽스를 나눠서
        awslogs-stream-prefix: "flask-app"

