version: '3'

services:
  app:
    image: flask-personalassistant-app
    build: .
    ports:
      - "5000"
    entrypoint:
      python
    command: [
      "app.py"
    ]

  nginx:
    image: nginx
    ports:
      - "80"  #동적포트 바인딩  호스트머신에서 접속하기위한 동적 포트를 찾아내서 접속해야함 만약 50:50 안하면  ## ecs 도 동적 포트 바인딩 해야해 안그러면 여러개 올라갈때 두번째 부터는 이미 쓰고 있는 포트가
    build: ./nginx   #폴더에 가서 알아서 읽음