version: '3'

volumes:
  dynamodb_data:

services:
  app:
    image: flask-personalassistant-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PYTHONBUFFERED: 1
      AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      AWS_DEFAULT_REGION: "us-east-2"
    command: gunicorn app:app -w 2 --threads 2 -b 0.0.0.0:5000

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    command: /bin/bash -c "sleep 10; exec nginx -g 'daemon off;'"

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8000"

  initializer:
    image: amazon/aws-cli
    volumes:
     - ./Settings/init.sh:/app/Settings/init.sh
    command: /app/Settings/init.sh
    entrypoint: /bin/sh
    environment:
      AWS_ACCESS_KEY_ID: "id"
      AWS_SECRET_ACCESS_KEY: "key"
      AWS_DEFAULT_REGION: "us-east-1"
