# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC/indeedclone.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gRPC/indeedclone.proto',
  package='indeedclone',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16gRPC/indeedclone.proto\x12\x0bindeedclone\"\x1d\n\rsearchRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"Y\n\tjobObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\t\x12\x0f\n\x07summary\x18\x05 \x01(\t\"6\n\x0esearchResponse\x12$\n\x04jobs\x18\x01 \x03(\x0b\x32\x16.indeedclone.jobObject2Q\n\njobService\x12\x43\n\x06Search\x12\x1a.indeedclone.searchRequest\x1a\x1b.indeedclone.searchResponse\"\x00\x62\x06proto3'
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='searchRequest',
  full_name='indeedclone.searchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='indeedclone.searchRequest.term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=68,
)


_JOBOBJECT = _descriptor.Descriptor(
  name='jobObject',
  full_name='indeedclone.jobObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='indeedclone.jobObject.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='indeedclone.jobObject.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='indeedclone.jobObject.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salary', full_name='indeedclone.jobObject.salary', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='indeedclone.jobObject.summary', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=159,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='searchResponse',
  full_name='indeedclone.searchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobs', full_name='indeedclone.searchResponse.jobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=215,
)

_SEARCHRESPONSE.fields_by_name['jobs'].message_type = _JOBOBJECT
DESCRIPTOR.message_types_by_name['searchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['jobObject'] = _JOBOBJECT
DESCRIPTOR.message_types_by_name['searchResponse'] = _SEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

searchRequest = _reflection.GeneratedProtocolMessageType('searchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'gRPC.indeedclone_pb2'
  # @@protoc_insertion_point(class_scope:indeedclone.searchRequest)
  })
_sym_db.RegisterMessage(searchRequest)

jobObject = _reflection.GeneratedProtocolMessageType('jobObject', (_message.Message,), {
  'DESCRIPTOR' : _JOBOBJECT,
  '__module__' : 'gRPC.indeedclone_pb2'
  # @@protoc_insertion_point(class_scope:indeedclone.jobObject)
  })
_sym_db.RegisterMessage(jobObject)

searchResponse = _reflection.GeneratedProtocolMessageType('searchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'gRPC.indeedclone_pb2'
  # @@protoc_insertion_point(class_scope:indeedclone.searchResponse)
  })
_sym_db.RegisterMessage(searchResponse)



_JOBSERVICE = _descriptor.ServiceDescriptor(
  name='jobService',
  full_name='indeedclone.jobService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=217,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='indeedclone.jobService.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBSERVICE)

DESCRIPTOR.services_by_name['jobService'] = _JOBSERVICE

# @@protoc_insertion_point(module_scope)
